### PR TITLE
Enable github actions to generate PDF

### PR DESCRIPTION
**Pull request by jscheid-ventana**
This enables building the document with no local environment setup and more reproducibility.

The workflow is set up to trigger on pushes to main, as well as for pull requests.  I think the workflow can also be triggered for other branches once this is merged to main.

I think using github actions in this manner gets us started.  But longer term we should instead define a container Dockerfile/image that is to be used, as that would be more portable outside of github, and is also directly useful for local development.

The PDF is uploaded as an artifact, which can then be attached to releases.

### CODE REVIEW

**Comment by jscheid-ventana** [comment]
@jjscheel @elisa-riscv Comments on this approach?

**Comment by jscheid-ventana** [comment]
> Apologies, it had looked like the Ruby build was removed, however upon closer examination it looks like it was added back in later. 

Yes, please don't attempt to follow all of the commits, as I haven't squashed any of the development history.  Just take a look at the net changes.

Using a Dockerfile and a container will take some more learning and work if a sufficient image isn't already maintained, as we'd need to decide how to publish it, keep it in a org-specific registry, etc.

It'd be nice to adopt something consistent, including with riscv-isa-manual https://github.com/riscv/riscv-isa-manual/blob/master/.travis.yml.

It'd like to enable spec authors to edit and build specs completely using github UI, thus first implementing this github workflow method, but also enabling local workflows.

**Comment by jscheid-ventana** [comment]
Now you can see the latest action in my origin fork here:

https://github.com/jscheid-ventana/docs-templates/actions/runs/1313392626

You can look at the logs, and open up the "pdf" artifact.

**Comment by elisa-riscv** [comment]
LGTM :-)

**Comment by cetola** [comment]
@jscheid-ventana please squash as you feel appropriate and I'll merge that squashed commit.

**Comment by jscheid-ventana** [comment]
I guess that means this project doesn't set "Allow squash merging".  Then I'll try squashing locally.

**Pull request merged**
